name: pasar_petani
version: 1.0.0+1
publish_to: none
description: Aplikasi penghubung Petani dengan Koperasi.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage:
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^0.22.0
  email_validator: ^2.1.17
  dio: ^5.3.3
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/